### ISSUE TITLE
Server not restarting at selected time showing error

### ISSUE THREAD

**Issue by Cosmicoofman** [GeheimagentNr1/AutoRestart#4]
**Versions**
Minecraft Version: 1.19.2
Minecraft Forge Version: 43.2.0
Mod Version: 2.0.1

**Log files**
```
[17:00:14] [Server thread/INFO] [de.ge.au.ut.ServerRestarter/]: Restart Server
[17:00:14] [Server thread/ERROR] [de.ge.au.ut.ServerRestarter/]: Auto Restart could not be done.
java.io.IOException: Cannot run program "": CreateProcess error=87, The parameter is incorrect
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1143) ~[?:?] {}
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1073) ~[?:?] {}
        at de.geheimagentnr1.auto_restart.util.ServerRestarter.restartServer(ServerRestarter.java:34) ~[AutoRestart-1.19.2-2.0.1.jar%23687!/:2.0.1] {re:classloading}
        at de.geheimagentnr1.auto_restart.handlers.ForgeEventHandler.handleServerStoppedEvent(ForgeEventHandler.java:65) ~[AutoRestart-1.19.2-2.0.1.jar%23687!/:2.0.1] {re:classloading}
        at de.geheimagentnr1.auto_restart.handlers.__ForgeEventHandler_handleServerStoppedEvent_ServerStoppedEvent.invoke(.dynamic) ~[AutoRestart-1.19.2-2.0.1.jar%23687!/:2.0.1] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:127) ~[forge-1.19.2-43.2.0-universal.jar%231178!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:690) ~[server-1.19.2-20220805.130853-srg.jar%231173!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerSeedMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%231173!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerSeedMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
Caused by: java.io.IOException: CreateProcess error=87, The parameter is incorrect
        at java.lang.ProcessImpl.create(Native Method) ~[?:?] {}
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:494) ~[?:?] {}
        at java.lang.ProcessImpl.start(ProcessImpl.java:159) ~[?:?] {}
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1110) ~[?:?] {}
        ... 11 more

```
**Describe the bug**
Server not restarting at Selected Time, Showing above error and don't understand what could be causing it

**Expected behaviour**
The Server to restart at the selected times 05:00 and 17:00

**Additional context**
The Pack does have over 500 Mods, we would like to include this in our server pack to allow people to have the server restart automatically when the server inevitably crashes.

**Comment by GeheimagentNr1** [comment]
The error occurs because restart.use\_external\_restart\_script and restart.restart\_command are not correctly configured.

Please follow these instructions to set up the mod:  
https://github.com/GeheimagentNr1/AutoRestart/wiki/Simple-Instructions
